# Form implementation generated from reading ui file '.\ui\auth.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(611, 559)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.loginEdit = QtWidgets.QLineEdit(parent=Form)
        self.loginEdit.setMinimumSize(QtCore.QSize(400, 30))
        self.loginEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.loginEdit.setObjectName("loginEdit")
        self.verticalLayout.addWidget(self.loginEdit, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.passwordEdit = QtWidgets.QLineEdit(parent=Form)
        self.passwordEdit.setMinimumSize(QtCore.QSize(400, 30))
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordEdit.setObjectName("passwordEdit")
        self.verticalLayout.addWidget(self.passwordEdit, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.loginButton = QtWidgets.QPushButton(parent=Form)
        self.loginButton.setMinimumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.loginButton.setFont(font)
        self.loginButton.setStyleSheet("\n"
"color: #fff;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.loginButton.setObjectName("loginButton")
        self.verticalLayout.addWidget(self.loginButton, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gostButton = QtWidgets.QPushButton(parent=Form)
        self.gostButton.setMinimumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gostButton.setFont(font)
        self.gostButton.setObjectName("gostButton")
        self.verticalLayout.addWidget(self.gostButton, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Авторизация"))
        self.title.setText(_translate("Form", "Вход в систему"))
        self.loginEdit.setPlaceholderText(_translate("Form", "Введите ваш логин"))
        self.passwordEdit.setPlaceholderText(_translate("Form", "Введите ваш пароль"))
        self.loginButton.setText(_translate("Form", "Войти"))
        self.gostButton.setText(_translate("Form", "Войти как гость"))
