# Form implementation generated from reading ui file '.\ui\item_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 480)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(parent=Dialog)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.nameLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.nameLineEdit)
        self.descriptionLabel = QtWidgets.QLabel(parent=Dialog)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.descriptionLabel)
        self.descriptionLineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.descriptionLineEdit.setObjectName("descriptionLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.descriptionLineEdit)
        self.priceLabel = QtWidgets.QLabel(parent=Dialog)
        self.priceLabel.setObjectName("priceLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.priceLabel)
        self.priceDoubleSpinBox = QtWidgets.QDoubleSpinBox(parent=Dialog)
        self.priceDoubleSpinBox.setMinimum(100.0)
        self.priceDoubleSpinBox.setMaximum(5000.0)
        self.priceDoubleSpinBox.setSingleStep(100.0)
        self.priceDoubleSpinBox.setObjectName("priceDoubleSpinBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.priceDoubleSpinBox)
        self.categoryLabel = QtWidgets.QLabel(parent=Dialog)
        self.categoryLabel.setObjectName("categoryLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.categoryLabel)
        self.categoryComboBox = QtWidgets.QComboBox(parent=Dialog)
        self.categoryComboBox.setObjectName("categoryComboBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.categoryComboBox)
        self.imageLabel = QtWidgets.QLabel(parent=Dialog)
        self.imageLabel.setObjectName("imageLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.imageLabel)
        self.imageLineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.imageLineEdit.setEnabled(False)
        self.imageLineEdit.setObjectName("imageLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.imageLineEdit)
        self.uploadImageButton = QtWidgets.QPushButton(parent=Dialog)
        self.uploadImageButton.setObjectName("uploadImageButton")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.uploadImageButton)
        self.verticalLayout.addLayout(self.formLayout)
        self.applyButton = QtWidgets.QPushButton(parent=Dialog)
        self.applyButton.setObjectName("applyButton")
        self.verticalLayout.addWidget(self.applyButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Работа с блюдом"))
        self.nameLabel.setText(_translate("Dialog", "Имя"))
        self.descriptionLabel.setText(_translate("Dialog", "Состав"))
        self.priceLabel.setText(_translate("Dialog", "Цена"))
        self.categoryLabel.setText(_translate("Dialog", "Категория"))
        self.imageLabel.setText(_translate("Dialog", "Изображение"))
        self.uploadImageButton.setText(_translate("Dialog", "Загрузить изображение"))
        self.applyButton.setText(_translate("Dialog", "Выполнить"))
